name: shopper_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  rxdart: ^0.27.7
  fan_carousel_image_slider: ^0.1.2
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  dio: ^5.4.3
  awesome_dio_interceptor: ^1.2.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_rating_stars: ^1.1.0
  lottie: ^3.1.2
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
